
import React, { useState, useEffect } from 'react';
import { Files } from '../types';
import { Icon } from './Icon';

interface PublishModalProps {
  projectName: string;
  files: Files;
  onClose: () => void;
}

type Step = 'oauth' | 'config' | 'publishing' | 'success' | 'error';

const PublishModal: React.FC<PublishModalProps> = ({ projectName, files, onClose }) => {
  const [step, setStep] = useState<Step>('oauth');
  const [repoName, setRepoName] = useState(projectName.replace(/[^a-z0-9-]/gi, '-'));
  const [isPrivate, setIsPrivate] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [statusText, setStatusText] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const [successUrl, setSuccessUrl] = useState('');
  const [githubUser, setGithubUser] = useState<any>(null);

  useEffect(() => {
    // Sanitize project name for repo name
    setRepoName(projectName.replace(/[^a-z0-9-]/gi, '-'));
  }, [projectName]);

  // Check for OAuth callback on component mount
  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const githubAuth = urlParams.get('github_auth');
    const error = urlParams.get('message');

    if (githubAuth === 'success') {
      // Clean URL and proceed to config
      window.history.replaceState({}, document.title, window.location.pathname);
      setStep('config');
    } else if (githubAuth === 'error') {
      // Clean URL and show error
      window.history.replaceState({}, document.title, window.location.pathname);
      setErrorMessage(error || 'GitHub authentication failed');
      setStep('error');
    }
  }, []);

  const handleOAuthLogin = async () => {
    setIsLoading(true);
    setErrorMessage('');

    try {
      // Redirect to GitHub OAuth
      window.location.href = 'https://mominai-4.vercel.app/api/auth/github';
    } catch (error) {
      setErrorMessage('Failed to initiate GitHub authentication');
      setIsLoading(false);
    }
  };

  const handlePublish = async () => {
    setIsLoading(true);
    setErrorMessage('');
    setStep('publishing');

    try {
      setStatusText('Publishing project to GitHub...');

      const response = await fetch('/api/github/publish', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', // Include cookies for session
        body: JSON.stringify({
          projectName: repoName,
          files,
          isPrivate,
          description: `Project generated by MominAI`,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || 'Failed to publish project');
      }

      setSuccessUrl(data.repository.html_url);
      setStep('success');

    } catch (error) {
      console.error('Publishing error:', error);
      setErrorMessage(error instanceof Error ? error.message : 'An unknown error occurred during publishing.');
      setStep('error');
    } finally {
      setIsLoading(false);
    }
  };

  const resetToOAuth = () => {
    setStep('oauth');
    setErrorMessage('');
  };

  const renderContent = () => {
    switch (step) {
      case 'oauth':
        return (
          <>
            <h3 className="text-xl font-bold mb-2">Connect to GitHub</h3>
            <p className="text-sm text-gray-400 mb-4">
              To publish your project, you'll be redirected to GitHub to authorize this application.
            </p>
            <p className="text-xs text-gray-500 mb-6">
              We'll request permission to create repositories and push code on your behalf.
            </p>
            {errorMessage && <p className="text-red-400 text-sm mb-4">{errorMessage}</p>}
            <button
              onClick={handleOAuthLogin}
              disabled={isLoading}
              className="w-full p-3 text-sm font-semibold rounded-lg bg-purple-600 hover:bg-purple-500 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
            >
              <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
              {isLoading ? 'Redirecting...' : 'Continue with GitHub'}
            </button>
          </>
        );
      case 'config':
        return (
          <>
            <h3 className="text-xl font-bold mb-4">Configure Repository</h3>
            <div className="mb-4">
              <label htmlFor="repoName" className="block text-sm font-medium text-gray-400 mb-1">
                Repository Name
              </label>
              <input
                id="repoName"
                type="text"
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                className="w-full bg-black/40 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
              />
            </div>
            <div className="mb-6 flex items-center justify-between bg-black/40 rounded-lg p-3">
              <label htmlFor="repoVisibility" className="text-sm text-gray-400">
                Private Repository
              </label>
              <button
                onClick={() => setIsPrivate(!isPrivate)}
                className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                  isPrivate ? 'bg-purple-600' : 'bg-gray-600'
                }`}
              >
                <span
                  className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                    isPrivate ? 'translate-x-6' : 'translate-x-1'
                  }`}
                />
              </button>
            </div>
            <button
              onClick={handlePublish}
              disabled={isLoading}
              className="w-full p-3 text-sm font-semibold rounded-lg bg-purple-600 hover:bg-purple-500 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors"
            >
              {isLoading ? 'Publishing...' : 'Create & Publish'}
            </button>
          </>
        );
      case 'publishing':
        return (
          <div className="text-center">
            <h3 className="text-xl font-bold mb-4">Publishing Project...</h3>
            <div className="dot-pulse flex space-x-2 justify-center my-4">
              <span className="w-2.5 h-2.5 bg-purple-300 rounded-full"></span>
              <span className="w-2.5 h-2.5 bg-purple-300 rounded-full"></span>
              <span className="w-2.5 h-2.5 bg-purple-300 rounded-full"></span>
            </div>
            <p className="text-gray-400">{statusText}</p>
          </div>
        );
      case 'success':
        return (
          <div className="text-center">
            <h3 className="text-xl font-bold mb-4 text-green-400">Published Successfully!</h3>
            <p className="text-gray-400 mb-6">Your project is now live on GitHub.</p>
            <a
              href={successUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="w-full block p-3 text-sm font-semibold rounded-lg bg-purple-600 hover:bg-purple-500 transition-colors"
            >
              View Repository
            </a>
          </div>
        );
      case 'error':
        return (
          <div className="text-center">
            <h3 className="text-xl font-bold mb-4 text-red-400">Publishing Failed</h3>
            <p className="text-gray-400 mb-6 bg-red-900/50 p-3 rounded-lg">{errorMessage}</p>
            <button
              onClick={resetToOAuth}
              className="w-full p-3 text-sm font-semibold rounded-lg bg-purple-600 hover:bg-purple-500 transition-colors"
            >
              Try Again
            </button>
          </div>
        );
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md" role="dialog" aria-modal="true">
      <div className="relative w-full max-w-md bg-gray-800/80 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-2xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1 rounded-full text-gray-400 hover:bg-white/10 hover:text-white"
          aria-label="Close"
        >
          <Icon name="close" className="w-5 h-5" />
        </button>
        {renderContent()}
      </div>
    </div>
  );
};

export default PublishModal;
