import { throwIfEnvInvalid } from '../../lib/env.js';

interface ImageGenerationRequest {
  prompt: string;
}

interface ImageGenerationResponse {
  success: boolean;
  imageUrl: string;
  prompt: string;
  timestamp: number;
}

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  // Validate environment variables
  throwIfEnvInvalid();

  const { prompt }: ImageGenerationRequest = req.body;

  if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
    return res.status(400).json({ message: 'Prompt is required and must be a non-empty string' });
  }

  const GEMINI_API_KEY = process.env.GEMINI_API_KEY || 'AIzaSyAj-c3pIvRYBtGjWN0UBTSYVGHnbpeka5Y';

  if (!GEMINI_API_KEY) {
    console.error("CRITICAL ERROR: GEMINI_API_KEY environment variable is not set");
    return res.status(500).json({ message: 'Server configuration error: Gemini API key is missing.' });
  }

  try {
    // Use Gemini 2.5 Flash Image model for image generation
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-exp-image:generateContent?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt.trim()
          }]
        }],
        generationConfig: {
          responseModalities: ['Text', 'Image']
        }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
      console.error('Gemini API error:', errorData);
      return res.status(response.status).json({
        message: `Gemini API error: ${errorData.error?.message || 'Failed to generate image'}`
      });
    }

    const data = await response.json();

    if (!data.candidates || !data.candidates[0] || !data.candidates[0].content || !data.candidates[0].content.parts) {
      console.error('Invalid response from Gemini:', data);
      return res.status(500).json({ message: 'Invalid response from image generation service' });
    }

    // Find the image part in the response
    const imagePart = data.candidates[0].content.parts.find((part: any) => part.inlineData);

    if (!imagePart || !imagePart.inlineData || !imagePart.inlineData.data) {
      console.error('No image data found in Gemini response:', data);
      return res.status(500).json({ message: 'No image generated by Gemini' });
    }

    // Convert base64 to a data URL
    const base64Image = imagePart.inlineData.data;
    const imageUrl = `data:image/png;base64,${base64Image}`;

    const result: ImageGenerationResponse = {
      success: true,
      imageUrl,
      prompt: prompt.trim(),
      timestamp: Date.now(),
    };

    res.status(200).json(result);

  } catch (error: any) {
    console.error('Error generating image with Gemini:', error);
    res.status(500).json({
      message: 'An error occurred while generating the image.',
      error: error.message
    });
  }
}