import jwt from 'jsonwebtoken';
import cookie from 'cookie';
import { createRepo, pushFiles, getUserRepos } from '../../services/githubService.js';

const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';
const BASE_URL = 'https://mominai-4.vercel.app';

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  try {
    // Verify user session
    const cookies = cookie.parse(req.headers.cookie || '');
    const sessionToken = cookies.session;

    if (!sessionToken) {
      return res.status(401).json({ message: 'Authentication required' });
    }

    // Decode session token
    const decoded = jwt.verify(sessionToken, JWT_SECRET) as any;
    const { githubAccessToken, githubUser } = decoded;

    if (!githubAccessToken || !githubUser) {
      return res.status(401).json({ message: 'GitHub authentication required' });
    }

    const { projectName, files, isPrivate = false, description = 'Project generated by MominAI' } = req.body;

    if (!projectName || !files || typeof files !== 'object') {
      return res.status(400).json({
        message: 'Missing required fields: projectName and files are required'
      });
    }

    // Check if repository already exists
    const userRepos = await getUserRepos(githubAccessToken);
    const existingRepo = userRepos.find((repo: any) => repo.name === projectName);

    let repo;
    if (existingRepo) {
      repo = existingRepo;
    } else {
      // Create new repository
      try {
        repo = await createRepo(githubAccessToken, projectName, isPrivate);
      } catch (error) {
        if (error instanceof Error && error.message.includes('name already exists')) {
          return res.status(409).json({
            message: 'A repository with this name already exists on your GitHub account'
          });
        }
        throw error;
      }
    }

    // Prepare files for GitHub (ensure they are strings)
    const filesToPush: { [path: string]: string } = {};
    for (const [path, content] of Object.entries(files)) {
      filesToPush[path] = typeof content === 'string' ? content : JSON.stringify(content, null, 2);
    }

    // Push files to repository
    const commitMessage = `Initial commit: ${description}`;
    await pushFiles(githubAccessToken, githubUser.login, projectName, filesToPush, commitMessage);

    // Return success response
    res.status(200).json({
      success: true,
      repository: {
        name: repo.name,
        full_name: repo.full_name,
        html_url: repo.html_url,
        clone_url: repo.clone_url,
        ssh_url: repo.ssh_url,
        private: repo.private,
        description: repo.description,
        created_at: repo.created_at,
        updated_at: repo.updated_at,
      },
      message: existingRepo
        ? 'Project files updated successfully'
        : 'Project published to GitHub successfully'
    });

  } catch (error) {
    console.error('GitHub publishing error:', error);

    if (error instanceof Error) {
      if (error.message.includes('Invalid or expired')) {
        return res.status(401).json({ message: 'GitHub token expired. Please re-authenticate.' });
      }
      if (error.message.includes('Repository creation failed')) {
        return res.status(400).json({ message: error.message });
      }
      if (error.message.includes('name already exists')) {
        return res.status(409).json({ message: error.message });
      }
    }

    res.status(500).json({
      message: 'Failed to publish project to GitHub',
      error: error instanceof Error ? error.message : 'Unknown error'
    });
  }
}